From tomcat:8.0-jre8-alpine

ADD docker/bin/rest-user-service /usr/local/tomcat/webapps/user/
ADD docker/setenv.sh /usr/local/tomcat/bin/
ADD docker/userConfig.json /usr/local/tomcat/webapps/user/WEB-INF/

