---
# Source: palisade/templates/etcd.yaml
kind: Service
apiVersion: v1
metadata:
  labels:
    app:  etcd
  name: etcd
spec:
  selector:
    app: etcd
  ports:
    - protocol: TCP
      port: 2379
      targetPort: 2379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: etcd
  name: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  etcd
  template:
    metadata:
      name: etcd
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: example_etcd:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 0.5
              memory: 2Gi
          ports:
            - containerPort: 2379
          livenessProbe:
            httpGet:
              path: /health
              port: 2379
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 2379
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
      restartPolicy: Always

