#!/usr/bin/env sh
#login to the ecr registry
$(aws ecr get-login --no-include-email --region eu-west-1)
aws eks --region eu-west-1 update-kubeconfig --name created-from-eksctl
mkdir ~/tiller_logs

export TILLER_NAMESPACE=tiller
export HELM_HOST=:44134
nohup tiller -listen=localhost:44134 -storage=secret -log_dir ~/tiller_logs > ~/tiller_logs/tiller-command.log &
sleep 20
helm init --client-only
helm repo update
