apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app:  configure-example
  name: configure-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  configure-example
  template:
    metadata:
      labels:
        app:  configure-example
    spec:
      containers:
      - image: configure-example
        name: configure-example
        resources: {}
      restartPolicy: Always
status: {}
