apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: data-service
  name: data-service-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
