---
# Source: palisade/templates/data-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app:  data-service
  name: data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  data-service
  template:
    metadata:
      labels:
        app:  data-service
    spec:
      containers:
      - image: tmppalisadeopsuksouthacr.azurecr.io/data-service:latest
        livenessProbe:
          httpGet:
            path: /data/v1/status
            port: 8080
          failureThreshold: 5
          periodSeconds: 60
          timeoutSeconds: 10
        name: data-service
        volumeMounts:
        - mountPath: /data
          name: data-service-claim0
      restartPolicy: Always
      volumes:
      - name: data-service-claim0
        persistentVolumeClaim:
          claimName: data-service-claim0
