apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: policy-service
  name: policy-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: policy-service
    spec:
      containers:
      - image: policy-service
        livenessProbe:
          httpGet: 
            path: /policy/v1/status
            port: 8080
          failureThreshold: 5
          periodSeconds: 60
          timeoutSeconds: 10
        name: policy-service
        resources: {}
      restartPolicy: Always
status: {}
