apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: resource-service-claim0
  name: resource-service-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi