kind: Service
apiVersion: v1
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - image: user-service
        livenessProbe:
          httpGet:
            path: /user/v1/status
            port: 8080
          failureThreshold: 5
          periodSeconds: 60
          timeoutSeconds: 10
        name: user-service
        resources: {}
      restartPolicy: Always
