steps:
- checkout: none
- task: DownloadBuildArtifacts@0
  displayName: 'Download Build Artifacts'
  inputs:
    buildType: specific
    project: '124362e9-66a7-42ba-922e-4971f592dea1'
    pipeline: 43
    specificBuildWithTriggering: true
    artifactName: docker
    downloadPath: '$(System.ArtifactsDirectory)'

- task: Docker@0
  displayName: 'Build  ${{ parameters.imageName }} image'
  inputs:
    azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
    azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
    dockerFile: '$(System.ArtifactsDirectory)/docker/example-docker-services/${{ parameters.imageName }}/Dockerfile'
    imageName: '${{ parameters.imageName }}:$(Build.BuildId)'
    includeLatestTag: true

- task: Docker@0
  displayName: 'Push ${{ parameters.imageName }} image'
  inputs:
    azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
    azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
    action: 'Push an image'
    imageName: '${{ parameters.imageName }}:$(Build.BuildId)'
    includeLatestTag: true
