# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java


stages:
- stage: Maven_Build  
  jobs:
  - job:
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        goals: 'clean install'

- stage: Docker_Build_and_Push 
  jobs:
    - job:
      pool:
        vmImage: 'Ubuntu-16.04'
      steps:
      - task: Docker@0
        displayName: 'Build client image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          dockerFile: 'example/deployment/local-docker/example-docker-services/client/Dockerfile'
          imageName: 'client:$(Build.BuildId)'
          includeLatestTag: true

      - task: Docker@0
        displayName: 'Push client image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          action: 'Push an image'
          imageName: 'client:$(Build.BuildId)'
          includeLatestTag: true

    - job:
      pool:
        vmImage: 'Ubuntu-16.04'
      steps:          
      - task: Docker@0
        displayName: 'Build config-service image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          dockerFile: 'example/deployment/local-docker/example-docker-services/config-service/Dockerfile'
          imageName: 'config-service:$(Build.BuildId)'
          includeLatestTag: true

      - task: Docker@0
        displayName: 'Push config-service image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          action: 'Push an image'
          imageName: 'config-service:$(Build.BuildId)'
          includeLatestTag: true

    - job:
      pool:
        vmImage: 'Ubuntu-16.04'
      steps:
      - task: Docker@0
        displayName: 'Build configure-example image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          dockerFile: 'example/deployment/local-docker/example-docker-services/configure-example/Dockerfile'
          imageName: 'configure-example:$(Build.BuildId)'
          includeLatestTag: true



      - task: Docker@0
        displayName: 'Push configure-example image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          action: 'Push an image'
          imageName: 'configure-example:$(Build.BuildId)'
          includeLatestTag: true

    - job:
      pool:
        vmImage: 'Ubuntu-16.04'
      steps:
      - task: Docker@0
        displayName: 'Build configure-services image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          dockerFile: 'example/deployment/local-docker/example-docker-services/configure-services/Dockerfile'
          imageName: 'configure-services:$(Build.BuildId)'
          includeLatestTag: true

      - task: Docker@0
        displayName: 'Push configure-services image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          action: 'Push an image'
          imageName: 'configure-services:$(Build.BuildId)'
          includeLatestTag: true

    - job:
      pool:
        vmImage: 'Ubuntu-16.04'
      steps:  

      - task: Docker@0
        displayName: 'Build data-service image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          dockerFile: 'example/deployment/local-docker/example-docker-services/data-service/Dockerfile'
          imageName: 'data-service:$(Build.BuildId)'
          includeLatestTag: true

      - task: Docker@0
        displayName: 'Push data-service image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          action: 'Push an image'
          imageName: 'data-service:$(Build.BuildId)'
          includeLatestTag: true

    - job:
      pool:
        vmImage: 'Ubuntu-16.04'
      steps:
      - task: Docker@0
        displayName: 'Build etcd image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          dockerFile: 'example/deployment/local-docker/example-docker-services/etcd/Dockerfile'
          imageName: 'etcd:$(Build.BuildId)'
          includeLatestTag: true

      - task: Docker@0
        displayName: 'Push etcd image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          action: 'Push an image'
          imageName: 'etcd:$(Build.BuildId)'
          includeLatestTag: true

    - job:
      pool:
        vmImage: 'Ubuntu-16.04'
      steps:
      - task: Docker@0
        displayName: 'Build palisade-service image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          dockerFile: 'example/deployment/local-docker/example-docker-services/palisade-service/Dockerfile'
          imageName: 'palisade-service:$(Build.BuildId)'
          includeLatestTag: true

      - task: Docker@0
        displayName: 'Push palisade-service image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          action: 'Push an image'
          imageName: 'palisade-service:$(Build.BuildId)'
          includeLatestTag: true

    - job:
      pool:
        vmImage: 'Ubuntu-16.04'
      steps:
      - task: Docker@0
        displayName: 'Build policy-service image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          dockerFile: 'example/deployment/local-docker/example-docker-services/policy-service/Dockerfile'
          imageName: 'policy-service:$(Build.BuildId)'
          includeLatestTag: true

      - task: Docker@0
        displayName: 'Push policy-service image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          action: 'Push an image'
          imageName: 'policy-service:$(Build.BuildId)'
          includeLatestTag: true

    - job:
      pool:
        vmImage: 'Ubuntu-16.04'
      steps:
      - task: Docker@0
        displayName: 'Build resource-service image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          dockerFile: 'example/deployment/local-docker/example-docker-services/resource-service/Dockerfile'
          imageName: 'resource-service:$(Build.BuildId)'
          includeLatestTag: true

      - task: Docker@0
        displayName: 'Push resource-service image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          action: 'Push an image'
          imageName: 'resource-service:$(Build.BuildId)'
          includeLatestTag: true

    - job:
      pool:
        vmImage: 'Ubuntu-16.04'
      steps:
      - task: Docker@0
        displayName: 'Build rest-redirector image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          dockerFile: 'example/deployment/local-docker/example-docker-services/rest-redirector/Dockerfile'
          imageName: 'rest-redirector:$(Build.BuildId)'
          includeLatestTag: true

      - task: Docker@0
        displayName: 'Push rest-redirector image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          action: 'Push an image'
          imageName: 'rest-redirector:$(Build.BuildId)'
          includeLatestTag: true

    - job:
      pool:
        vmImage: 'Ubuntu-16.04'
      steps:
      - task: Docker@0
        displayName: 'Build user-service image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          dockerFile: 'example/deployment/local-docker/example-docker-services/user-service/Dockerfile'
          imageName: 'user-service:$(Build.BuildId)'
          includeLatestTag: true

      - task: Docker@0
        displayName: 'Push user-service image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          action: 'Push an image'
          imageName: 'user-service:$(Build.BuildId)'
          includeLatestTag: true

    - job:
      pool:
        vmImage: 'Ubuntu-16.04'
      steps:
      - task: Docker@0
        displayName: 'Build palisade-service image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          dockerFile: 'example/deployment/local-docker/example-docker-services/palisade-service/Dockerfile'
          imageName: 'palisade-service:$(Build.BuildId)'
          includeLatestTag: true

      - task: Docker@0
        displayName: 'Push palisade-service image'
        inputs:
          azureSubscription: 'Demos (802df257-6032-4b50-884c-55cb9f074928)'
          azureContainerRegistry: '{"loginServer":"marcusreg.azurecr.io", "id" : "/subscriptions/802df257-6032-4b50-884c-55cb9f074928/resourceGroups/DevOpsDemo-ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/marcusreg"}'
          action: 'Push an image'
          imageName: 'palisade-service:$(Build.BuildId)'
          includeLatestTag: true
