---
# Source: palisade/templates/palisade-service.yaml
kind: Service
apiVersion: v1
metadata:
  labels:
    app: palisade-service
  name:  palisade-service
spec:
  type: LoadBalancer
  selector:
    app: palisade-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
     app: palisade-service
  name: palisade-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  palisade-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: palisade-service
    spec:
      containers:
      - name: palisade-service
        image: palisadeacr.azurecr.io/palisade-service:latest
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 0.5
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /palisade/v1/status
            port: 8080
          failureThreshold: 5
          periodSeconds: 60
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /palisade/v1/status
            port: 8080
          failureThreshold: 5
          periodSeconds: 60
          timeoutSeconds: 10
      restartPolicy: Always
