---
# Source: palisade/templates/policy-service.yaml

kind: Service
apiVersion: v1
metadata:
  labels:
    app: policy-service
  name: policy-service
spec:
  selector:
    app: policy-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: policy-service
  name: policy-service
spec:
  replicas: {{ .Values.policy-service.replicas }}
  selector:
    matchLabels:
      app:  policy-service
  template:
    metadata:
      labels:
        app:  policy-service
    spec:
      containers:
      - name: policy-service
        image: "{{ .Values.policy-service.image.repository }}:{{ .Values.policy-service.image.tag }}"
        imagePullPolicy: "{{ .Values.policy-service.image.pullPolicy }}"
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet: 
            path: /policy/v1/status
            port: 8080
          failureThreshold: 5
          periodSeconds: 60
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /policy/v1/status
            port: 8080
          failureThreshold: 5
          periodSeconds: 60
          timeoutSeconds: 10
        resources:
          {{- toYaml .Values.policy-service.resources | nindent 12 }}
      restartPolicy: Always
status: {}
