---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: config-service
  name: config-service
spec:
  selector:
    app: config-service
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: config-service
  name: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  config-service
  template:
    metadata:
      name: config-service
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: example_config-service:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 0.5
              memory: 2Gi
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /config/v1/status
              port: 8080
            failureThreshold: 5
            periodSeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /config/v1/status
              port: 8080
            failureThreshold: 5
            periodSeconds: 60
            timeoutSeconds: 10
      restartPolicy: Always

