From tomcat:8.0-jre8-alpine

ADD docker/bin/rest-policy-service /usr/local/tomcat/webapps/policy/
ADD docker/setenv.sh /usr/local/tomcat/bin/
ADD docker/policyConfig.json /usr/local/tomcat/webapps/policy/WEB-INF/

