apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: jenkins-pv
  labels:
     type: amazonEBS 
spec:
  capacity:
    storage: "11Gi" 
  accessModes:
    - "ReadWriteOnce"
    - "ReadOnlyMany"
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /ebs-data/jenkins
