apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: jenkins-pv
  labels:
     type: amazonEBS 
spec:
  capacity:
    storage: "5Gi" 
  storageClassName: standard
  accessModes:
    - "ReadWriteOnce"
  awsElasticBlockStore: 
    fsType: "ext4" 
    volumeID: "vol-Insert Vol ID here" 

