apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8081'
spec:
  selector: 
    app: nexus-server
  type: NodePort  
  ports:
  - port: 8081
    nodePort: 31751
    protocol: TCP
    targetPort: 8081
  selector:
    app: nexus-server

