From tomcat:8-jre11-slim

ADD docker/bin/rest-resource-service /usr/local/tomcat/webapps/resource/
ADD docker/setenv.sh /usr/local/tomcat/bin/
ADD docker/bin/configRest.json /usr/local/tomcat/webapps/resource/WEB-INF/

