From tomcat:8.0-jre8-alpine

ADD docker/bin/rest-resource-service /usr/local/tomcat/webapps/resource/
ADD docker/setenv.sh /usr/local/tomcat/bin/
ADD docker/resourceConfig.json /usr/local/tomcat/webapps/resource/WEB-INF/

