version: "3"

services:

   stage-build:
     build: stage-build
     container_name: stage-build
     volumes:
        - "./data-service/:/data-vol"
        - "./palisade-service/:/palisade-vol"
        - "./policy-service/:/policy-vol"
        - "./resource-service/:/resource-vol"
        - "./user-service/:/user-vol"
        - "./config-service/:/config-vol"
   data-service:
     build:
       context: data-service
       dockerfile: ../../../deployment/docker/data-service/Dockerfile
     container_name: data-service
     ports:
        - 8084:8080
     depends_on:
        - stage-build
   config-service:
        build:
          context: config-service
          dockerfile: ../../../deployment/docker/config-service/Dockerfile
        container_name: config-service
        ports:
           - 8085:8080
        depends_on:
           - stage-build
   user-service:
     build:
       context: user-service
       dockerfile: ../../../deployment/docker/user-service/Dockerfile
     container_name: user-service
     ports:
        - 8083:8080
     depends_on:
        - stage-build
   resource-service:
     build:
       context: resource-service
       dockerfile: ../../../deployment/docker/resource-service/Dockerfile
     container_name: resource-service
     ports:
        - 8082:8080
     depends_on:
        - stage-build
   policy-service:
     build:
       context: policy-service
       dockerfile: ../../../deployment/docker/policy-service/Dockerfile
     container_name: policy-service
     ports:
        - 8081:8080
     depends_on:
        - stage-build
   palisade-service:
     build:
       context: palisade-service
       dockerfile: ../../../deployment/docker/palisade-service/Dockerfile
     container_name: palisade-service
     ports:
        - 8080:8080
     depends_on:
        - stage-build
        - policy-service
        - resource-service
        - user-service
        - data-service
        - config-service