From tomcat:8.0-jre8-alpine

ADD docker/bin/rest-palisade-service /usr/local/tomcat/webapps/palisade/
ADD docker/setenv.sh /usr/local/tomcat/bin/
ADD docker/palisadeConfig.json /usr/local/tomcat/webapps/palisade/WEB-INF/

