kind: Service
apiVersion: v1
metadata:
  labels:
    app: config-service
  name: config-service
spec:
  selector:
    app: config-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: config-service
  name: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  config-service
  template:
    metadata:
      labels:
         app:  config-service
    spec:
      containers:
      - image: {{ .Values.image.registry }}/config-service:{{ .Values.image.tag }}
        livenessProbe:
          httpGet:
            path: /config/v1/status
            port: 8080
          failureThreshold: 5
          periodSeconds: 60
          timeoutSeconds: 10
        name: config-service
        resources: {}
      restartPolicy: Always
status: {}
