---
# Source: palisade/templates/configure-services.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app:  configure-services
  name: configure-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  configure-services
  template:
    metadata:
      labels:
        app:  configure-services
    spec:
      containers:
      - image: tmppalisadeopsuksouthacr.azurecr.io/configure-services:latest
        name: configure-services
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
          - name: config
            mountPath: /mnt/config
      restartPolicy: Always
      volumes:
      - name: config
        azureFile:
          secretName: config-share-secret
          shareName: config
          readOnly: true
          
status: {}