kind: Service
apiVersion: v1
metadata:
  app:  etcd
spec:
  selector:
    app: etcd
  ports:
  - protocol: TCP
    port: 2379
    targetPort: 2379
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app:  etcd
  name: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - image: {{ .Values.image.registry }}/etcd:{{ .Values.image.tag }}
        livenessProbe:
          httpGet:
            path: /health
            port: 2379
          failureThreshold: 5
          periodSeconds: 60
          timeoutSeconds: 10
        name: etcd
        resources: {}
      restartPolicy: Always
status: {}
