kind: Service
apiVersion: v1
metadata:
  name: palisade-service
spec:
  selector:
    app: palisade-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
     app: palisade-service
  name: palisade-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  palisade-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: palisade-service
    spec:
      containers:
      - image: {{ .Values.image.registry }}/palisade-service:{{ .Values.image.tag }}
        livenessProbe:
          httpGet:
            path: /palisade/v1/status
            port: 8080
          failureThreshold: 5
          periodSeconds: 60
          timeoutSeconds: 10
        name: palisade-service
        resources: {}
      restartPolicy: Always
