
kind: Service
apiVersion: v1
metadata:
  labels:
    app: policy-service
  name: policy-service
spec:
  selector:
    app: policy-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: policy-service
  name: policy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  policy-service
  template:
    metadata:
      labels:
        app:  policy-service
    spec:
      containers:
      - image: {{ .Values.image.registry }}/policy-service:{{ .Values.image.tag }}
        livenessProbe:
          httpGet: 
            path: /policy/v1/status
            port: 8080
          failureThreshold: 5
          periodSeconds: 60
          timeoutSeconds: 10
        name: policy-service
        resources: {}
      restartPolicy: Always
status: {}
