apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: name-virtual-host-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /config
            backend:
              serviceName: config-service
              servicePort: 8080
    - http:
        paths:
          - path: /palisade
            backend:
              serviceName: palisade-service
              servicePort: 8080
    - http:
        paths:
          - path: /data
            backend:
              serviceName: data-service
              servicePort: 8080
